version: '3.8'

services:
  # 应用服务 (生产环境)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bun-hono-server-prod
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - /root/envs/hono/.env  # 生产环境配置文件路径
    environment:
      # 强制设置生产环境变量
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # 仅挂载必要的文件 (生产环境不建议使用本地存储)
      - ./logs:/app/logs
      # 如果使用本地文件上传，取消下行注释
      # - ./uploads:/app/uploads
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    # 安全配置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/data  # 临时数据目录
    networks:
      - app-network

networks:
  app-network:
    driver: bridge